spring:
  profiles:
    active:
    - dev
---
server:
  port: 9003
spring:
  profiles: dev  #开发环境
  application:
    name: mini-db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 9003
spring:
  profiles: test  #测试环境
  application:
    name: mini-db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/